build:
  version: "2.0"

loans:
  message: "Welcome to SamBank cards related local APIs"
  contactDetails:
    name: "Samridhi Parihar-qa"
    email: "samparihar@gmail.com"
  onCallSupport:
    - "qa: 9142*****"
    - "qa: 8357*****"