build:
  version: "3.0"

loans:
  message: "Welcome to SamBank cards related local APIs"
  contactDetails:
    name: "Samridhi Parihar-prod"
    email: "samparihar@gmail.com"
  onCallSupport:
    - "prod: 9142*****"
    - "prod: 8357*****"